[package]
name = "game_math"
version = "0.1.0"
edition = "2024"
license = "Zlib OR MIT OR Apache-2.0"

[dependencies]
bytemuck = { version = "1.23.2", features = ["derive"] }
contiguous_bitset = "0.1.1"
randomize = { version = "5.1.0", features = ["getrandom"] }
